./5-main.py
Exception raised

